backend:
  name: github
  repo: Trailblazer-Analytics/trailblazer-analytics-web
  branch: main
  auth_type: pkce # Uses GitHub App authentication
  
# Editorial workflow: creates PRs instead of direct commits
publish_mode: editorial_workflow

# Media files configuration
media_folder: "public/images"
public_folder: "/images"

# File slug configuration
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

# Collections configuration
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{fields.slug}}"
    preview_path: "/blog/{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Slug must be lowercase, alphanumeric, with hyphens only'] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Published Date (Legacy)", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD", required: false }
      - { label: "Author", name: "author", widget: "string", default: "Alexander Nykolaiszyn" }
      - { label: "Tags", name: "tags", widget: "list", default: [], allow_add: true }
      - { label: "Featured Image", name: "image", widget: "image", required: false, media_folder: "/public/images", public_folder: "/images" }
      - { label: "Hero Image", name: "heroImage", widget: "image", required: false, media_folder: "/public/images", public_folder: "/images" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Vibe", name: "vibe", widget: "select", options: ["technical", "rant", "insight", "story", "hot-take"], required: false }
      - { label: "Reading Time", name: "readingTime", widget: "number", required: false }
      - { label: "Difficulty", name: "difficulty", widget: "select", options: ["beginner", "intermediate", "advanced", "expert"], required: false }
      - { label: "Category", name: "category", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "downloads"
    label: "Downloads"
    folder: "src/content/downloads"
    create: true
    slug: "{{fields.slug}}"
    preview_path: "/downloads/{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Slug must be lowercase, alphanumeric, with hyphens only'] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["Templates", "Tools", "Guides", "Checklists", "Frameworks", "Whitepapers", "AI & Advanced Analytics", "AI & Machine Learning", "Architecture & Strategy", "Data Strategy", "Sustainability & Strategy"], required: false }
      - { label: "File Type", name: "fileType", widget: "string", required: false }
      - { label: "File Size", name: "fileSize", widget: "string", required: false }
      - { label: "Download URL", name: "downloadUrl", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5, required: false }
      - { label: "Downloads Count", name: "downloads", widget: "number", required: false }
      - { label: "Image", name: "image", widget: "image", required: false, media_folder: "/public/images", public_folder: "/images" }
      - { label: "Pages", name: "pages", widget: "number", required: false }
      - { label: "Free", name: "free", widget: "boolean", default: true }
      - { label: "Gated", name: "gated", widget: "boolean", default: false }
      - { label: "Table of Contents", name: "tableOfContents", widget: "list", required: false, allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "tools"
    label: "Tools"
    folder: "src/content/tools"
    create: true
    slug: "{{fields.slug}}"
    preview_path: "/tools/{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', 'Slug must be lowercase, alphanumeric, with hyphens only'] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["Frameworks", "Templates", "Calculators", "Courses", "Premium Tools"], required: false }
      - { label: "Price", name: "price", widget: "string", required: false }
      - { label: "Demo URL", name: "demoUrl", widget: "string", required: false }
      - { label: "Purchase URL", name: "purchaseUrl", widget: "string", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 5, required: false }
      - { label: "Technologies", name: "technologies", widget: "list", required: false, allow_add: true }
      - { label: "Features", name: "features", widget: "list", required: false, allow_add: true }
      - { label: "Image", name: "image", widget: "image", required: false, media_folder: "/public/images", public_folder: "/images" }
      - { label: "Tags", name: "tags", widget: "list", default: [], allow_add: true }
      - { label: "Gated", name: "gated", widget: "boolean", default: true }
      - { label: "Premium", name: "premium", widget: "boolean", default: false }
      - { label: "Gateway Type", name: "gatewayType", widget: "select", options: ["newsletter", "purchase"], required: false }
      - { label: "Body", name: "body", widget: "markdown" }

# Site settings
site_url: https://trailblazeranalytics.com
display_url: https://trailblazeranalytics.com
logo_url: https://trailblazeranalytics.com/images/trailblazer-logo.jpg